/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;


// import chess.connection.EventPump;
import chess.model.*;
import chess.connection.*;
import java.util.Scanner;
// import java.util.ArrayDeque;
// import java.util.logging.Level;
// import java.util.logging.Logger;

public class App {
    public static void main(String[] args) {
        TestBot bot = new TestBot("INSERT TOKEN HERE");
     
        Scanner scanner = new Scanner(System.in); 
        while (true){
            String input = scanner.nextLine();
            if (input.equalsIgnoreCase("xboard")){
                XBoardHandler xb = new XBoardHandler(bot);
                while (true){
                    if (scanner.nextLine().startsWith("protover")){
                        System.out.append("feature sigint=0 sigterm=0 reuse=0 usermove=1 myname=\"tiraengine\" done=1\n");
                        System.out.flush();
                        break;
                    }
                }
                xb.run();
                
            } else if (input.equalsIgnoreCase("lichess")){
                scanner.close();
                LichessAPI api = new LichessAPI(bot);
                
                Profile myProfile = api.getAccount();
                
                System.out.println("Profile ID: " + myProfile.id);
                
                api.beginEventLoop();
            }
            
        }
        
    }
}
