/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

// import chess.connection.EventPump;
import chess.connection.LichessAPI;
import chess.model.Profile;
// import java.io.IOException;
// import java.util.ArrayDeque;
// import java.util.logging.Level;
// import java.util.logging.Logger;

public class App {
    public static void main(String[] args) {
        LichessAPI api = new LichessAPI("6iqx5TbL0QsFyqxR");
        
        Profile myProfile = api.getAccount();
        
        System.out.println("Profile ID: " + myProfile.id);
    }
}
