/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

// import chess.connection.EventPump;
import chess.connection.LichessAPI;
import chess.model.Profile;
import logging.Logger;

public class App {
    public static void main(String[] args) {
        TestBot bot = new TestBot("INSERT TOKEN HERE");
        
        LichessAPI api = new LichessAPI(bot);
        Logger logger = new Logger().useStdOut();
        
        Profile myProfile = api.getAccount();
        
        logger.logMessage("Profile ID: " + myProfile.id);
        
        api.beginEventLoop();
    }
}
